# Default configuration for Pylon Dashboard
local_port = 6989
token = "your_default_token"
name = "Local Pylon"
location = "City, ST"
description = "Some description of your pylon, visible both locally and remote when the pylon is clicked."

# New auto-update options:
auto_update = true
master_update_url = "https://brinstar.top/pylon"


[[remote_pylons]]
ip = "http://www.website.com"
port = 6989
token = "some_remote_token"
name = "Remote Pylon Name"

