# Default configuration for Pylon Dashboard
local_port = 6989
token = "your_default_token"
name = "Local Pylon"
location = "City, ST"
description = "Some description of your pylon, visible both locally and remote when the pylon is clicked."

# New auto-update options:
auto_update = true
master_update_url = "https://brinstar.top/pylon"

