name: Update Language Badges

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Language Data
        run: |
          curl -s https://api.github.com/repos/saintpetejackboy/pylon/languages > languages.json

      - name: Ensure Rust, CSS, JavaScript, and HTML Always Exist
        run: |
          echo '{"Rust":0,"CSS":0,"JavaScript":0,"HTML":0}' > default.json
          jq -s 'add' default.json languages.json > merged.json
          mv merged.json languages.json

      - name: Calculate Percentages
        run: |
          TOTAL=$(jq 'reduce .[] as $num (0; . + $num)' languages.json)
          jq 'to_entries | map({key: .key, value: ((.value / $TOTAL) * 100)})' --argjson TOTAL "$TOTAL" languages.json > lang_percent.json

      - name: Generate Language Badges
        run: |
          declare -A COLORS
          COLORS=( ["Rust"]="orange" ["JavaScript"]="yellow" ["HTML"]="blue" ["CSS"]="blue" )

          echo "[![Top Language](https://img.shields.io/github/languages/top/saintpetejackboy/pylon)](https://github.com/saintpetejackboy/pylon)" > README_BADGES.md
          jq -r '.[] | "[![\(.key)](https://img.shields.io/badge/\(.key)-\(.value|round)%25-" + (env.COLORS[\(.key)] // "blue") + ")](#)"' lang_percent.json >> README_BADGES.md

      - name: Update README.md
        run: |
          awk '/<!-- BADGES_START -->/,/<!-- BADGES_END -->/ {next} {print}' README.md > README_TMP.md
          mv README_TMP.md README.md
          echo "<!-- BADGES_START -->" >> README.md
          cat README_BADGES.md >> README.md
          echo "<!-- BADGES_END -->" >> README.md

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add README.md
          if ! git diff --cached --exit-code; then
            git commit -m "Auto-update language badges"
            git push
          else
            echo "No changes to commit"
          fi
