name: Update Language Badges

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Language Data
        run: |
          curl -s https://api.github.com/repos/saintpetejackboy/pylon/languages > languages.json

      - name: Ensure Rust, CSS, JavaScript, and HTML Always Exist
        run: |
          echo '{"Rust":0,"CSS":0,"JavaScript":0,"HTML":0}' > default.json
          jq -s 'add' default.json languages.json > merged.json
          mv merged.json languages.json

      - name: Calculate Percentages
        run: |
          TOTAL=$(jq '[.[]] | add' languages.json)
          jq --argjson total "$TOTAL" 'to_entries | map({key: .key, value: ((.value / $total) * 100)})' languages.json > lang_percent.json

      - name: Debug: Show Generated Language Percentages
        run: cat lang_percent.json

      - name: Generate Language Badges
        run: |
          echo "[![Top Language](https://img.shields.io/github/languages/top/saintpetejackboy/pylon)](https://github.com/saintpetejackboy/pylon)" > README_BADGES.md
          
          jq -r '.[] | "\(.key)=\(.value | round)"' lang_percent.json || echo "Rust=0" > lang_percent.tmp

          while IFS="=" read -r lang percent; do
            case "$lang" in
              Rust) color="orange" ;;
              JavaScript) color="yellow" ;;
              HTML) color="blue" ;;
              CSS) color="blue" ;;
              *) color="blue" ;;
            esac
            echo "[![${lang}](https://img.shields.io/badge/${lang}-${percent}%25-${color})](#)" >> README_BADGES.md
          done < <(jq -r '.[] | "\(.key)=\(.value | round)"' lang_percent.json)

      - name: Debug: Show Generated Badges
        run: cat README_BADGES.md

      - name: Update README.md
        run: |
          awk '/<!-- BADGES_START -->/,/<!-- BADGES_END -->/ {next} {print}' README.md > README_TMP.md
          mv README_TMP.md README.md
          echo "<!-- BADGES_START -->" >> README.md
          cat README_BADGES.md >> README.md
          echo "<!-- BADGES_END -->" >> README.md

      - name: Debug: Show Final README
        run: cat README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add README.md
          if ! git diff --cached --exit-code; then
            git commit -m "Auto-update language badges"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit"
          fi
